# Generated by Django 2.2.3 on 2019-07-24 21:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo_img', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.datetime(2019, 7, 24, 15, 38, 48, 151889))),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('sentiment', models.CharField(max_length=1)),
                ('review', models.CharField(blank=True, max_length=1, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Company')),
            ],
            options={
                'unique_together': {('company_id', 'title')},
            },
        ),
    ]
