# Generated by Django 2.2.3 on 2019-07-25 21:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190724_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 25, 21, 52, 58, 5029, tzinfo=utc)),
        ),
    ]
