# Generated by Django 2.2.3 on 2019-07-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190726_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='common_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
