# Generated by Django 2.2.3 on 2019-07-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_company_common_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='common_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
