# Generated by Django 2.2.3 on 2019-07-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20190726_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isFin',
            field=models.BooleanField(default=True),
        ),
    ]
