# Generated by Django 2.2.3 on 2019-07-29 04:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_article_isfin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date(2019, 7, 29)),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2019, 7, 29))),
                ('price', models.FloatField(default=0.0)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Company')),
            ],
            options={
                'unique_together': {('company_id', 'date')},
            },
        ),
    ]
