# Generated by Django 2.2.3 on 2019-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190728_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
