# Generated by Django 2.2.3 on 2019-07-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20190729_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='p_ind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='p_neg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='p_pos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
