# Generated by Django 2.2.3 on 2019-07-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20190729_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_blank_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
