# Generated by Django 2.2.3 on 2019-07-30 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20190730_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sentiment',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
