# Generated by Django 2.2.3 on 2019-07-31 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20190730_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_checked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
